package com.citiustech.mrr;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
@javax.persistence.Table(name = "Error_Msg")
public class ErrorMsg implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("errorCode")
	private java.lang.Integer errorCode;
	@org.kie.api.definition.type.Label("errorMessage")
	private java.lang.String errorMessage;

	@javax.persistence.Id
	@javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "ERRORMSG_ID_GENERATOR")
	@javax.persistence.SequenceGenerator(name = "ERRORMSG_ID_GENERATOR", sequenceName = "ERRORMSG_ID_SEQ")
	private java.lang.Long id;

	public ErrorMsg() {
	}

	public java.lang.Integer getErrorCode() {
		return this.errorCode;
	}

	public void setErrorCode(java.lang.Integer errorCode) {
		this.errorCode = errorCode;
	}

	public java.lang.String getErrorMessage() {
		return this.errorMessage;
	}

	public void setErrorMessage(java.lang.String errorMessage) {
		this.errorMessage = errorMessage;
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public ErrorMsg(java.lang.Integer errorCode, java.lang.String errorMessage,
			java.lang.Long id) {
		this.errorCode = errorCode;
		this.errorMessage = errorMessage;
		this.id = id;
	}

}